"""Generate the browsable fault dictionary (docs/discovery-2-td5/fault-dictionary*.md).

Reads the fault-meaning store (src/d2diag/dtc/*.json) and renders one markdown page per
module plus an index — the RAVE fault-finding section, searchable and served by the
dashboard Documents tab (no UI build needed). Generated: never hand-edit; refine the
meanings in the `dtc` store and re-run.

    PYTHONPATH=src python3 tools/gen_fault_docs.py           # write the docs
    PYTHONPATH=src python3 tools/gen_fault_docs.py --check    # exit 1 if any page is stale (CI)
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from d2diag import dtc  # noqa: E402

_DOCS = Path(__file__).resolve().parents[1] / "docs" / "discovery-2-td5"
_TODAY = "2026-10-04"

# module → (slug, title, key-column header). Only modules with a dtc/<module>.json.
_MODULES = [
    ("td5", "fault-dictionary-td5", "Td5 engine fault dictionary", "Bit (off.bit)"),
    ("slabs", "fault-dictionary-slabs", "SLABS (ABS/SLS) fault dictionary", "Code"),
    ("airbag", "fault-dictionary-airbag", "Airbag (SRS) fault dictionary", "Code"),
    ("autobox", "fault-dictionary-autobox", "Auto gearbox (EAT) fault dictionary", "Code"),
    ("ace", "fault-dictionary-ace", "ACE fault dictionary", "Code"),
]


# How many codes each module can report, and how we know.
_TOTALS = {
    "td5": ("280 bits", "Vendor guide: \"over 200\" fault codes in a 35-byte (280-bit) block, so some "
                        "unnamed bits are probably spare."),
    "slabs": ("47", "Vendor guide: \"up to 47 different faults\". The rsw list (stored rsw-NNN) "
                    "is a different numbering with ~67 fault types."),
    "airbag": ("37", "Vendor guide: \"up to 37 faults\". The register's string dump spans "
                     "numbers 1–65, so the numbering is not simply 1–37."),
    "autobox": ("39", "Vendor guide: \"up to 39 different problems\"; RAVE table uses internal "
                      "numbers 1–39 (36 absent)."),
    "ace": ("45", "Vendor guide: \"up to 45 different problems\" (some shown as MASKED FAULT). "
                  "Store counts three display schemes for the same faults."),
}
# Totals source: NanoCom vendor ECU guides, https://www.blackbox-solutions.com/site/support
# (see references/d2-tool-cross-reference.md).


def _fm(title: str, summary: str) -> str:
    return (f"---\ntitle: \"{title}\"\narea: docs\nstatus: stable\nversion: 1.0\n"
            f"updated: {_TODAY}\nsummary: >\n  {summary}\n---\n\n")


def _cell(s: str) -> str:
    return (s or "").replace("|", r"\|").strip()


def _module_page(module: str, title: str, key_header: str) -> str:
    rows = dtc.load_records(module)
    body = [_fm(title, f"Generated fault dictionary for the {module} module — every known "
                       f"code with its meaning, likely cause, severity and (inferred) P-code. "
                       f"Generated from src/d2diag/dtc/{module}.json; do not hand-edit."),
            f"# {title}\n",
            "_Generated from the fault-meaning store (`src/d2diag/dtc/"
            f"{module}.json`) — do not edit by hand; refine the store and re-run "
            "`tools/gen_fault_docs.py`._\n",
            f"| {key_header} | Fault | Confidence | P-code | Severity | Meaning | Likely cause |",
            "|---|---|---|---|---|---|---|"]
    for r in rows:
        body.append(
            f"| `{_cell(r.get('key'))}` | {_cell(r.get('name'))} | "
            f"{_cell(r.get('confidence')) or '—'} | {_cell(r.get('pcode')) or '—'} | {_cell(r.get('severity')) or '—'} | "
            f"{_cell(r.get('description'))} | {_cell(r.get('cause'))} |")
    body.append("")
    return "\n".join(body) + "\n"


def _index_page() -> str:
    body = [_fm("Discovery 2 fault dictionary",
                "Index of the per-module fault dictionaries — the meaning of every fault "
                "code, replacing the RAVE fault-finding section. Generated; do not hand-edit."),
            "# Discovery 2 fault dictionary\n",
            "The meaning of every known fault code per module — what it means, the likely "
            "cause, its severity and an inferred OBD-II P-code where one applies. This is the "
            "RAVE fault-finding section, rebuilt as a searchable store "
            "(`src/d2diag/dtc/`), served here and at the `/faults` endpoint.\n",
            "> Generated by `tools/gen_fault_docs.py` from `src/d2diag/dtc/*.json`. The Td5 "
            "is not OBD2, so a P-code is an inferred cross-reference, not a code the ECU "
            "emits. Meanings are documented facts (see each row's source in the store); a "
            "code→meaning pairing is only `proven` once verified on the car; everything from a "
            "forum or vendor list is `candidate`.\n"]
    body.append("| Dictionary | Codes in the store | Total that exist | How sure is the total |")
    body.append("|---|---|---|---|")
    for module, slug, title, _ in _MODULES:
        n = len(dtc.load_records(module))
        total, basis = _TOTALS[module]
        body.append(f"| [{title}]({slug}.md) | {n} | {total} | {basis} |")
    body.append("")
    return "\n".join(body) + "\n"


def _targets() -> "dict[Path, str]":
    out = {_DOCS / "fault-dictionary.md": _index_page()}
    for module, slug, title, key_header in _MODULES:
        out[_DOCS / f"{slug}.md"] = _module_page(module, title, key_header)
    return out


def main() -> int:
    check = "--check" in sys.argv
    stale = False
    for path, text in _targets().items():
        if check:
            cur = path.read_text(encoding="utf-8") if path.exists() else ""
            if cur != text:
                print(f"{path.relative_to(_DOCS.parents[1])} is stale — run "
                      "tools/gen_fault_docs.py", file=sys.stderr)
                stale = True
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(_DOCS.parents[1])}")
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
